name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
      value: "Brief description of the error"
    validations:
      required: true
  - type: textarea
      id: reproduce
      attributes:
        label: To Reproduce
        description: Steps to reproduce the behavior. Please list down all steps on how to reproduce the bug.
        placeholder: list all the steps to reproduce the error!
        value: "Steps to reproduce the error"
      validations:
        required: true
